name: "Docker build and push to ecr"
on: 
  workflow_call:
    inputs:
      BUILD-ARGS:
        required: false
        type: string
jobs: 
  dockerBuild-ECRpush:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Set env
        run: echo "ARTIFACT_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::603457443348:role/GithubActionsECRAccess
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Download jar artifact
        with:
          name: output-jar
        uses: actions/download-artifact@v3
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          build-args: ${{ inputs.BUILD-ARGS }}
          tags: "603457443348.dkr.ecr.eu-central-1.amazonaws.com/${{ github.event.repository.name }}:${{ env.ARTIFACT_IDENTIFIER }}"
      - name: Push image to ECR
        if: github.ref_name == 'master'
        run: "docker push 603457443348.dkr.ecr.eu-central-1.amazonaws.com/${{ github.event.repository.name }}:${ARTIFACT_IDENTIFIER}"
