name: "Docker build and push to ecr"
on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      needs-intermediate-artifact:
        required: false
        default: false
        type: boolean
      repo-name:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
jobs:
  dockerBuild-ECRpush:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "ARTIFACT_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::603457443348:role/GithubActionsECRAccess
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: 603457443348.dkr.ecr.eu-central-1.amazonaws.com
      - name: Download jar artifact
        if: inputs.needs-intermediate-artifact == true
        with:
          name: output-jar
        uses: actions/download-artifact@v3
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          build-args: ${{ inputs.build-args }}
          tags: "603457443348.dkr.ecr.eu-central-1.amazonaws.com/${{ inputs.repo-name }}:${{ env.ARTIFACT_IDENTIFIER }}"
      - name: Build and push
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: ${{ inputs.build-args }}
          tags: |
            "603457443348.dkr.ecr.eu-central-1.amazonaws.com/${{ inputs.repo-name }}:${{ env.ARTIFACT_IDENTIFIER }}"
            "603457443348.dkr.ecr.eu-central-1.amazonaws.com/${{ inputs.repo-name }}:latest"
