name: "Trigger jenkins infra script"
on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string
    secrets:
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "ARTIFACT_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Trigger jenkins infra script
        if: github.ref_name == 'master'
        uses: toptal/jenkins-job-trigger-action@master
        env:
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          PARAMETER_NAME: ${{ inputs.param }}
        run: "curl --location --request POST 'https://build.leanspace.io/jenkins/job/leanspace/job/leanspace-infra/job/master/buildWithParameters' \
          --header 'Authorization: Basic $JENKINS_TOKEN' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode '$PARAMETER_NAME=$ARTIFACT_IDENTIFIER'"
