name: "Trigger jenkins infra script"
on:
  workflow_call:
    inputs:
      project-code:
        required: true
        type: string
      version-identifier:
        required: true
        type: string
      run-tests:
        required: false
        type: boolean
        default: true
    secrets:
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true
jobs:
  infra:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Trigger jenkins infra script
        uses: fjogeleit/http-request-action@v1.8.2
        with:
          url: "https://build.leanspace.io/jenkins/job/leanspace/job/leanspace-infra/job/master/buildWithParameters"
          method: "POST"
          username: ${{ secrets.JENKINS_USER }}
          password: ${{ secrets.JENKINS_TOKEN }}
          data: ${{ format('{0}={1}&runIntegrationTests={2}', inputs.project-code, inputs.version-identifier, inputs.run-tests) }}
          customHeaders: '{ "Content-Type": "application/x-www-form-urlencoded" }'
