name: "Trigger jenkins infra script"
on:
  workflow_call:
    inputs:
      parameter_name:
        required: true
        type: string
      version_identifier:
        required: true
        type: string
    secrets:
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins infra script
        if: github.ref_name == 'master'
        uses: fjogeleit/http-request-action@v1.8.2
        with:
          url: 'https://build.leanspace.io/jenkins/job/leanspace/job/leanspace-infra/job/master/buildWithParameters'
          method: 'POST'
          username: ${{ secrets.JENKINS_USER }}
          password: ${{ secrets.JENKINS_TOKEN }}
          data: ${{ format('{0}={1}', inputs.parameter_name, inputs.version_identifier) }}
          customHeaders: '{ "Content-Type": "application/x-www-form-urlencoded" }'