name: "Trigger jenkins infra script"
on:
  workflow_call:
    inputs:
      project-code:
        required: true
        type: string
      version-identifier:
        required: true
        type: string
      run-tests:
        required: false
        type: boolean
        default: true
    secrets:
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        id: deployment
        with:
          ref: ${{ github.head_ref }}
          auto_merge: false
          required_contexts: ''
          environment: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger jenkins infra script
        uses: fjogeleit/http-request-action@v1.8.2
        with:
          url: "https://build.leanspace.io/jenkins/job/Leanspace-infra/job/master/buildWithParameters"
          method: "POST"
          username: ${{ secrets.JENKINS_USER }}
          password: ${{ secrets.JENKINS_TOKEN }}
          data: ${{ format('{0}={1}&runIntegrationTests={2}&deploymentId={3}', inputs.project-code, inputs.version-identifier, inputs.run-tests, steps.deployment.outputs.deployment_id) }}
          customHeaders: '{ "Content-Type": "application/x-www-form-urlencoded" }'
      - uses: avakar/set-deployment-status@v1
        with:
          state: in_progress
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          auto_inactive: false
          description: "Develop deployment in progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}