name: "Trigger jenkins infra script"
on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string
jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "ARTIFACT_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      - name: Trigger jenkins infra script
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "https://build.leanspace.io/jenkins/"
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: "leanspace/job/leanspace-infra/job/master"
          job_params: ${{ format('{0}={1}', inputs.param, env.ARTIFACT_IDENTIFIER) }}
          async: true
