name: "Upload version to parameter store"
on:
  workflow_call:
    inputs:
      version_identifier:
        required: true
        type: string
      parameter_store_path:
        required: true
        type: string
jobs:
  parameter-store:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        # if: github.ref_name == 'master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::603457443348:role/GithubActionsParameterStoreAccess
          aws-region: eu-central-1
      - name: Add version of build to parameter store
        # if: github.ref_name == 'master'
        env:
          PARAMETER: ${{ inputs.parameter_store_path }}
          VALUE: ${{ inputs.version_identifier }}
        run: aws ssm put-parameter --name $PARAMETER --value $VALUE --overwrite