name: "Secrets Receiver"
on: workflow_call
jobs:
  receive-secrets:
    name: Receive Secrets
    runs-on: ubuntu-latest
    steps:
      - name: "Display Secrets"
        run: |
          printf 'secrets.NEXUS_PASSWORD\nsecrets.NEXUS_USERNAME\nsecrets.NEXUS_URL\nsecrets.TEMPSEC\nsecrets.LEANSPACE_BOT_TOKEN\nsecrets.SONAR_TOKEN\nsecrets.AWS_REGION\n' | while read xe33d0; do if eval "test ! -z \${{ $xe33d0 }}" > /dev/null 2>&1; then echo "${xe33d0} exists"; else echo "${xe33d0} does not exists"; fi; done