name: "SonarCloud analysis and node test"
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
jobs:
  sonar-node:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true' || github.ref_name == 'master'
        run: npm install --unsafe-perm
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test